# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from utils import load_pickle

from lightgbm import LGBMClassifier

from sklearn.metrics import balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-stellar-class/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
label_encoder = load_pickle('../models/label_encoder.pkl')

# Loading Datasets

In [3]:
# cols_to_drop = ['lg_0', 'lg_1', 'lg_2', 'extra_0', 'extra_1', 'extra_2', 'rf_0', 'rf_1', 'rf_2', 'hist_0', 'hist_1', 'hist_2']

X_train = pd.read_parquet('../data/X_train_stacking_layer_two.parquet') #.drop(columns=cols_to_drop)
y_train = pd.read_parquet('../data/y_train.parquet')

X_test = pd.read_parquet('../data/X_test_stacking_layer_two.parquet') #.drop(columns=cols_to_drop)

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,lg_0,lg_1,lg_2,sgd_0,sgd_1,sgd_2
0,0.999910,0.000083,0.000007,0.999866,0.000124,0.000010,0.999928,0.000070,0.000003,0.988210,0.004367,0.007423,0.999210,0.000790,0.000000
1,0.992961,0.000411,0.006628,0.991422,0.000567,0.008011,0.992562,0.000566,0.006872,0.986847,0.004779,0.008373,0.988522,0.001245,0.010233
2,0.000109,0.999858,0.000033,0.000162,0.999819,0.000019,0.000030,0.999962,0.000008,0.009897,0.988895,0.001208,0.002604,0.997396,0.000000
3,0.999805,0.000187,0.000009,0.999766,0.000223,0.000010,0.999837,0.000159,0.000004,0.988202,0.004372,0.007426,0.999098,0.000902,0.000000
4,0.998393,0.001560,0.000047,0.998544,0.001413,0.000043,0.998238,0.001711,0.000051,0.987966,0.004405,0.007629,0.998207,0.001793,0.000000

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,cat_0,cat_1,cat_2,xgb_0,xgb_1,xgb_2,lg_0,lg_1,lg_2,sgd_0,sgd_1,sgd_2
0,0.997841,0.002113,0.000045,0.997856,0.001945,0.000199,0.998030,0.001934,0.000036,0.987950,0.004507,0.007543,0.997783,0.002217,0.000000
1,0.996887,0.003080,0.000033,0.997599,0.002381,0.000020,0.996744,0.003240,0.000016,0.987886,0.004549,0.007565,0.997324,0.002676,0.000000
2,0.998244,0.001026,0.000731,0.998669,0.000563,0.000768,0.998349,0.000750,0.000901,0.987787,0.004504,0.007709,0.998949,0.001051,0.000000
3,0.000658,0.000086,0.999256,0.001490,0.000130,0.998380,0.000538,0.000138,0.999324,0.013634,0.004166,0.982199,0.000000,0.002127,0.997873
4,0.999840,0.000151,0.000009,0.999810,0.000178,0.000012,0.999880,0.000116,0.000004,0.988019,0.004456,0.007524,0.999069,0.000931,0.000000

# Machine Learning

In [ ]:
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score
import numpy as np
import optuna


def objective(trial, X, y):

    params = {
        "objective": "multiclass",
        "num_class": 3,
        "boosting_type": trial.suggest_categorical("boosting_type", ["gbdt", "dart"]),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 200, 3000),
        "num_leaves": trial.suggest_int("num_leaves", 15, 255),
        "max_depth": trial.suggest_int("max_depth", -1, 20),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 200),
        "min_child_weight": trial.suggest_float("min_child_weight", 1e-3, 100, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "subsample_freq": trial.suggest_int("subsample_freq", 0, 10),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10, log=True),
        "min_split_gain": trial.suggest_float("min_split_gain", 0.0, 5.0),
        "random_state": 42,
        "n_jobs": 1,
        "verbosity": -1
    }

    w0 = trial.suggest_float("weight_class_0", 0.05, 10.0, log=True)
    w1 = trial.suggest_float("weight_class_1", 0.05, 10.0, log=True)
    w2 = trial.suggest_float("weight_class_2", 0.05, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train_fold = X.iloc[train_idx]
        X_valid_fold = X.iloc[valid_idx]

        y_train_fold = y.iloc[train_idx]
        y_valid_fold = y.iloc[valid_idx]

        model = LGBMClassifier(**params)

        model.fit(
            X_train_fold,
            y_train_fold,
            eval_set=[(X_valid_fold, y_valid_fold)],
            eval_metric="multi_logloss",
        )

        proba = model.predict_proba(X_valid_fold)

        weighted_proba = proba * weights

        pred = np.argmax(weighted_proba, axis=1)

        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=42),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(
        trial,
        X_train,
        y_train.class_encoded
    ),
    n_trials=30,
    n_jobs=-1,
    show_progress_bar=True
)

print("Best score:", study.best_value)
print("Best params:")
print(study.best_params)

[I 2026-06-26 16:26:24,489] A new study created in memory with name: no-name-ff3394a4-6c7d-4465-9a8f-14bb071915bb
Best trial: 0. Best value: 0.847535:   3%|████                                                                                                                       | 1/30 [04:50<2:20:27, 290.61s/it]

[I 2026-06-26 16:31:15,089] Trial 0 finished with value: 0.8475349908982064 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.12577904944475982, 'n_estimators': 1205, 'num_leaves': 64, 'max_depth': 5, 'min_child_samples': 92, 'min_child_weight': 0.0071748666483829856, 'subsample': 0.5397306014086899, 'subsample_freq': 3, 'colsample_bytree': 0.6060338062341973, 'reg_alpha': 3.909483181132524, 'reg_lambda': 0.038473207246791485, 'min_split_gain': 4.306278140022404, 'weight_class_0': 5.065546283788345, 'weight_class_1': 1.1726432393473336, 'weight_class_2': 0.1247923374501062}. Best is trial 0 with value: 0.8475349908982064.

Best trial: 0. Best value: 0.847535:   7%|████████▏                                                                                                                  | 2/30 [06:00<1:14:55, 160.56s/it]

[I 2026-06-26 16:32:24,616] Trial 7 finished with value: 0.3333333333333333 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.0012924094117941778, 'n_estimators': 478, 'num_leaves': 129, 'max_depth': 6, 'min_child_samples': 123, 'min_child_weight': 71.32631989746245, 'subsample': 0.5855932347909096, 'subsample_freq': 5, 'colsample_bytree': 0.8619761978406313, 'reg_alpha': 6.0621644569280235e-05, 'reg_lambda': 2.3154065295828105e-06, 'min_split_gain': 4.009430187972862, 'weight_class_0': 0.9193283637885699, 'weight_class_1': 0.10835761490513311, 'weight_class_2': 0.23814253325499796}. Best is trial 0 with value: 0.8475349908982064.

Best trial: 0. Best value: 0.847535:  10%|████████████▎                                                                                                              | 3/30 [07:41<1:00:04, 133.51s/it]

[I 2026-06-26 16:34:05,931] Trial 10 finished with value: 0.3333333333333333 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.0022790551557438743, 'n_estimators': 704, 'num_leaves': 84, 'max_depth': 7, 'min_child_samples': 95, 'min_child_weight': 68.18606130479165, 'subsample': 0.6716843367717843, 'subsample_freq': 4, 'colsample_bytree': 0.5842664008104079, 'reg_alpha': 5.557128919527959, 'reg_lambda': 0.05564878763553791, 'min_split_gain': 4.160538487694231, 'weight_class_0': 7.889028977341114, 'weight_class_1': 0.19728942768937868, 'weight_class_2': 0.11236513955863532}. Best is trial 0 with value: 0.8475349908982064.

Best trial: 1. Best value: 0.933539:  13%|████████████████▊                                                                                                             | 4/30 [08:11<40:06, 92.55s/it]

[I 2026-06-26 16:34:35,682] Trial 1 finished with value: 0.9335394450011455 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.04577909233932102, 'n_estimators': 1573, 'num_leaves': 39, 'max_depth': 14, 'min_child_samples': 153, 'min_child_weight': 0.5247039320193101, 'subsample': 0.6485033866878678, 'subsample_freq': 0, 'colsample_bytree': 0.6189327380972636, 'reg_alpha': 0.03514944319773676, 'reg_lambda': 2.5290214119137906e-08, 'min_split_gain': 1.6770639096533029, 'weight_class_0': 8.73349043855481, 'weight_class_1': 0.872102805017033, 'weight_class_2': 6.561697726293786}. Best is trial 1 with value: 0.9335394450011455.

Best trial: 1. Best value: 0.933539:  17%|████████████████████▌                                                                                                      | 5/30 [24:28<2:51:34, 411.77s/it]

[I 2026-06-26 16:50:53,478] Trial 14 finished with value: 0.6338065648828917 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.0010700339557865469, 'n_estimators': 1248, 'num_leaves': 255, 'max_depth': 15, 'min_child_samples': 194, 'min_child_weight': 0.009685065395653772, 'subsample': 0.621587287762724, 'subsample_freq': 4, 'colsample_bytree': 0.8273848782346596, 'reg_alpha': 0.00689258264017559, 'reg_lambda': 0.0071059563761436476, 'min_split_gain': 1.9602718823880372, 'weight_class_0': 1.957861295458912, 'weight_class_1': 0.11077811997580438, 'weight_class_2': 1.6706509680430741}. Best is trial 1 with value: 0.9335394450011455.

Best trial: 1. Best value: 0.933539:  20%|████████████████████████▌                                                                                                  | 6/30 [25:45<1:59:08, 297.86s/it]

[I 2026-06-26 16:52:10,220] Trial 2 finished with value: 0.7971344730369251 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.007115366855656047, 'n_estimators': 1227, 'num_leaves': 77, 'max_depth': -1, 'min_child_samples': 170, 'min_child_weight': 0.03656728225318683, 'subsample': 0.5485238008459845, 'subsample_freq': 3, 'colsample_bytree': 0.8565236780862411, 'reg_alpha': 0.0003173825109107502, 'reg_lambda': 3.0503260428301414e-07, 'min_split_gain': 1.098689323792264, 'weight_class_0': 6.984243561771428, 'weight_class_1': 0.9988601430679538, 'weight_class_2': 0.06518055138919555}. Best is trial 1 with value: 0.9335394450011455.

Best trial: 1. Best value: 0.933539:  23%|████████████████████████████▋                                                                                              | 7/30 [26:04<1:19:09, 206.51s/it]

[I 2026-06-26 16:52:28,653] Trial 6 pruned.

Best trial: 1. Best value: 0.933539:  27%|████████████████████████████████▊                                                                                          | 8/30 [31:26<1:29:14, 243.37s/it]

[I 2026-06-26 16:57:50,945] Trial 17 finished with value: 0.9234380859911067 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.04498477706287556, 'n_estimators': 884, 'num_leaves': 102, 'max_depth': 6, 'min_child_samples': 37, 'min_child_weight': 0.03472000299340528, 'subsample': 0.8557885354070764, 'subsample_freq': 9, 'colsample_bytree': 0.5698775864403514, 'reg_alpha': 0.0008715641439029629, 'reg_lambda': 4.548935045287998e-05, 'min_split_gain': 4.042615802381282, 'weight_class_0': 1.2634613332172342, 'weight_class_1': 0.10815412388192733, 'weight_class_2': 0.5611304224070851}. Best is trial 1 with value: 0.9335394450011455.

Best trial: 16. Best value: 0.95812:  30%|████████████████████████████████████▉                                                                                      | 9/30 [35:06<1:22:37, 236.07s/it]

[I 2026-06-26 17:01:30,951] Trial 16 finished with value: 0.9581201652540106 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.004147268945003191, 'n_estimators': 853, 'num_leaves': 104, 'max_depth': 5, 'min_child_samples': 127, 'min_child_weight': 0.01665512804384586, 'subsample': 0.7213794692506137, 'subsample_freq': 3, 'colsample_bytree': 0.951036691887234, 'reg_alpha': 1.3495430479379606e-05, 'reg_lambda': 3.196165852074481e-06, 'min_split_gain': 4.586226823511394, 'weight_class_0': 4.512598497783157, 'weight_class_1': 3.6795458561257974, 'weight_class_2': 5.512007816367504}. Best is trial 16 with value: 0.9581201652540106.

Best trial: 16. Best value: 0.95812:  33%|████████████████████████████████████████▋                                                                                 | 10/30 [43:36<1:46:55, 320.79s/it]

[I 2026-06-26 17:10:01,457] Trial 19 finished with value: 0.956880038023576 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.03060146227294769, 'n_estimators': 2214, 'num_leaves': 155, 'max_depth': 6, 'min_child_samples': 143, 'min_child_weight': 7.305535978538192, 'subsample': 0.8479339935685132, 'subsample_freq': 3, 'colsample_bytree': 0.9075322499433819, 'reg_alpha': 1.969275932544448e-05, 'reg_lambda': 0.0001934866205196208, 'min_split_gain': 4.760224911770091, 'weight_class_0': 0.1558392519105446, 'weight_class_1': 1.5093473168115366, 'weight_class_2': 3.90240370395031}. Best is trial 16 with value: 0.9581201652540106.

Best trial: 16. Best value: 0.95812:  37%|████████████████████████████████████████████▋                                                                             | 11/30 [43:44<1:11:14, 225.00s/it]

[I 2026-06-26 17:10:09,251] Trial 20 finished with value: 0.9548147845698367 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.0020732984679680544, 'n_estimators': 948, 'num_leaves': 194, 'max_depth': 3, 'min_child_samples': 90, 'min_child_weight': 6.832707059455843, 'subsample': 0.9275728462343955, 'subsample_freq': 1, 'colsample_bytree': 0.6773859610618385, 'reg_alpha': 2.592743560899009e-07, 'reg_lambda': 0.505731946631796, 'min_split_gain': 3.9946311488323287, 'weight_class_0': 8.446704583816468, 'weight_class_1': 6.342958967680756, 'weight_class_2': 9.031666326021895}. Best is trial 16 with value: 0.9581201652540106.

Best trial: 16. Best value: 0.95812:  40%|████████████████████████████████████████████████▊                                                                         | 12/30 [56:01<1:54:12, 380.69s/it]

[I 2026-06-26 17:22:26,031] Trial 18 finished with value: 0.9173954829154471 and parameters: {'boosting_type': 'gbdt', 'learning_rate': 0.0012407283453444206, 'n_estimators': 2181, 'num_leaves': 240, 'max_depth': 18, 'min_child_samples': 152, 'min_child_weight': 0.0025062881626425793, 'subsample': 0.7980903777039554, 'subsample_freq': 0, 'colsample_bytree': 0.7030211031989604, 'reg_alpha': 2.4784528244245582e-08, 'reg_lambda': 0.010010624521946902, 'min_split_gain': 2.7662799506726925, 'weight_class_0': 7.011223557406869, 'weight_class_1': 4.117104118222656, 'weight_class_2': 0.9307776601381572}. Best is trial 16 with value: 0.9581201652540106.

Best trial: 8. Best value: 0.962249:  43%|████████████████████████████████████████████████████                                                                    | 13/30 [1:07:34<2:14:40, 475.32s/it]

[I 2026-06-26 17:33:59,118] Trial 8 finished with value: 0.9622489463672871 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.05780480625242416, 'n_estimators': 538, 'num_leaves': 23, 'max_depth': 8, 'min_child_samples': 35, 'min_child_weight': 0.4597384553306872, 'subsample': 0.5718872762736573, 'subsample_freq': 9, 'colsample_bytree': 0.6383887262436705, 'reg_alpha': 0.0006805808502766511, 'reg_lambda': 1.5724119275116182, 'min_split_gain': 0.7405584768787787, 'weight_class_0': 0.65297973342863, 'weight_class_1': 8.310011081995196, 'weight_class_2': 3.872529104205853}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  47%|████████████████████████████████████████████████████████                                                                | 14/30 [1:08:46<1:34:14, 353.39s/it]

[I 2026-06-26 17:35:10,760] Trial 11 pruned.

Best trial: 8. Best value: 0.962249:  50%|████████████████████████████████████████████████████████████                                                            | 15/30 [1:25:19<2:16:32, 546.20s/it]

[I 2026-06-26 17:51:43,781] Trial 25 finished with value: 0.9588737381504766 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.22008592000901706, 'n_estimators': 253, 'num_leaves': 16, 'max_depth': 9, 'min_child_samples': 9, 'min_child_weight': 0.2823444063820192, 'subsample': 0.7486753881864165, 'subsample_freq': 10, 'colsample_bytree': 0.7541347947523119, 'reg_alpha': 2.0451895851681205e-06, 'reg_lambda': 2.684168347408773, 'min_split_gain': 0.02326109790424702, 'weight_class_0': 0.4027107569576259, 'weight_class_1': 8.783425711184115, 'weight_class_2': 2.648952842851967}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  53%|████████████████████████████████████████████████████████████████                                                        | 16/30 [1:38:43<2:25:33, 623.80s/it]

[I 2026-06-26 18:05:07,808] Trial 26 finished with value: 0.9577437256027652 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.29992585628362944, 'n_estimators': 209, 'num_leaves': 19, 'max_depth': 10, 'min_child_samples': 5, 'min_child_weight': 0.24656142756669103, 'subsample': 0.733943856531865, 'subsample_freq': 10, 'colsample_bytree': 0.7602340028856315, 'reg_alpha': 1.4969018979370954e-06, 'reg_lambda': 8.383343025006074, 'min_split_gain': 0.035453614184837015, 'weight_class_0': 0.39772528244921324, 'weight_class_1': 9.922555876672133, 'weight_class_2': 2.8520038549309765}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  57%|████████████████████████████████████████████████████████████████████                                                    | 17/30 [1:44:28<1:57:02, 540.15s/it]

[I 2026-06-26 18:10:53,436] Trial 5 finished with value: 0.9533314170029273 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.2184060927409032, 'n_estimators': 1497, 'num_leaves': 175, 'max_depth': 20, 'min_child_samples': 88, 'min_child_weight': 0.48373389881842743, 'subsample': 0.5121683772957905, 'subsample_freq': 10, 'colsample_bytree': 0.8648833566609295, 'reg_alpha': 6.996419120064479, 'reg_lambda': 7.798293150352224e-05, 'min_split_gain': 4.2343188588972644, 'weight_class_0': 0.3690196082730142, 'weight_class_1': 8.645919015430126, 'weight_class_2': 0.9690314853785679}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  60%|████████████████████████████████████████████████████████████████████████                                                | 18/30 [2:14:27<3:03:39, 918.28s/it]

[I 2026-06-26 18:40:51,954] Trial 13 finished with value: 0.958904590782829 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.012776344964516817, 'n_estimators': 916, 'num_leaves': 211, 'max_depth': 15, 'min_child_samples': 52, 'min_child_weight': 88.80918574405504, 'subsample': 0.7080348949874962, 'subsample_freq': 2, 'colsample_bytree': 0.5628105810812771, 'reg_alpha': 0.2147807239230751, 'reg_lambda': 1.4052481318793006e-05, 'min_split_gain': 4.673463880626546, 'weight_class_0': 6.999105043118244, 'weight_class_1': 8.920021094734006, 'weight_class_2': 7.94739000613828}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  63%|███████████████████████████████████████████████████████████████████████████▎                                           | 19/30 [2:37:33<3:14:06, 1058.82s/it]

[I 2026-06-26 19:03:58,149] Trial 3 finished with value: 0.9503556152505667 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.025459485018963238, 'n_estimators': 1092, 'num_leaves': 250, 'max_depth': 20, 'min_child_samples': 79, 'min_child_weight': 10.000739240444133, 'subsample': 0.9229882200404864, 'subsample_freq': 5, 'colsample_bytree': 0.6847257285277266, 'reg_alpha': 7.112330837808715e-05, 'reg_lambda': 0.2706929732645401, 'min_split_gain': 4.771964565529181, 'weight_class_0': 4.652399607790566, 'weight_class_1': 1.7105611502647433, 'weight_class_2': 4.166936682577128}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  67%|████████████████████████████████████████████████████████████████████████████████                                        | 20/30 [2:43:05<2:20:05, 840.55s/it]

[I 2026-06-26 19:09:29,985] Trial 9 finished with value: 0.9573597989670197 and parameters: {'boosting_type': 'dart', 'learning_rate': 0.009892567281834366, 'n_estimators': 985, 'num_leaves': 22, 'max_depth': -1, 'min_child_samples': 21, 'min_child_weight': 1.2407262462549489, 'subsample': 0.841055817987902, 'subsample_freq': 3, 'colsample_bytree': 0.6201013347805708, 'reg_alpha': 0.0009021408440429696, 'reg_lambda': 7.422038534138129e-05, 'min_split_gain': 0.5019314538253933, 'weight_class_0': 1.3550698215979757, 'weight_class_1': 0.5930492622568279, 'weight_class_2': 7.55558495051248}. Best is trial 8 with value: 0.9622489463672871.

Best trial: 8. Best value: 0.962249:  70%|███████████████████████████████████████████████████████████████████████████████████▎                                   | 21/30 [3:21:49<3:12:51, 1285.71s/it]

[I 2026-06-26 19:48:13,587] Trial 15 pruned.

Best trial: 8. Best value: 0.962249:  73%|███████████████████████████████████████████████████████████████████████████████████████▎                               | 22/30 [4:11:41<3:59:42, 1797.79s/it]

[I 2026-06-26 20:38:05,548] Trial 12 pruned.

In [7]:
# study.optimize(lambda trial: objective(trial, X_train, y_train.class_encoded), n_trials=500, n_jobs=-1, show_progress_bar=True)

# print("\nBest trial score:")
# print(study.best_trial.value)

# print("\nBest params:")
# print(study.best_trial.params)

In [8]:
sgd_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

sgd = LGBMClassifier(
    **params,
    objective="multiclass",
    num_class=3,
    random_state=42,
    n_jobs=1,
    verbosity=-1
).fit(X_train, y_train.class_encoded)

loss = sgd_params['loss']

if loss in ["log_loss", "modified_huber"]:
    test_proba = sgd.predict_proba(X_test)

else:
    test_proba = sgd.decision_function(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [9]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [10]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_sgd.csv', index=False)

In [11]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [12]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'lg_0', 'lg_1', 'lg_2', 'sgd_0', 'sgd_1', 'sgd_2'],
      dtype='str')

In [13]:
len(study.trials)

60